services:
  keycloack:
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: " -v start-dev"


